import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Poppins } from "next/font/google";
import { Providers } from "./providers";
import NavBar from "@/components/common/NavBar";
import { AuthService } from "@/helpers/auth/auth_api_wrappers";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ weight: ["400", "600"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const isAuthenticated = AuthService.validateAuth();
  return (
    <html lang="en" className="dark">
      <body className="h-screen bg-background" suppressHydrationWarning={true}>
        {isAuthenticated && <NavBar />}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
