export enum SocketEvent {
  CONNECTION = "connection",
  DISCONNECT = "disconnect",
  JOIN_ROOM = "join_room",
  CODE_CHANGE = "code_change",
  CODE_UPDATE = "code_update",
  CODE_EVENT = "code_event",
  SEND_CODE_EVENT = "send_code_event",
  SEND_CHAT_MESSAGE = "send_chat_message",
  UPDATE_CHAT_MESSAGE = "update_chat_message",
  END_SESSION = "end_session",
  CONFIRM_END_SESSION = "confirm_end_session",
  SESSION_TIMER = "session_timer",
  GET_SESSION_TIMER = "get_session_timer",
  PARTNER_CONNECTION = "partner_connection",
  UPDATE_CHAT_LIST = "update_chat_list",
  ROOM_NOT_FOUND = "room_not_found",
  USER_NOT_VALID = "user_not_valid",
  PARTNER_LEFT = "partner_left",
  SEND_CURSOR_CHANGE = "send_cursor_change",
  CURSOR_CHANGE = "cursor_change",
  SEND_HIGHLIGHT_CHANGE = "send_highlight_change",
  HIGHLIGHT_CHANGE = "highlight_change",
}
